---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: alpha
  namespace: default
  labels:
    {{- include "components.labels" . | nindent 4 }}
    gwcp.guidewire.com/app-name: alpha
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: {{ .Values.alpha.values.version | quote }}
    gwcp.guidewire.com/created-by: pod-avondale
    gwcp.guidewire.com/maintained-by: pod-avondale
    gwcp.guidewire.com/dept: {{ .Values.departmentCode | quote }}
spec:
  interval: 10m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alpha
  namespace: default
  labels:
    {{- include "components.labels" . | nindent 4 }}
    gwcp.guidewire.com/app-name: alpha
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: {{ .Values.alpha.values.version | quote }}
    gwcp.guidewire.com/created-by: pod-avondale
    gwcp.guidewire.com/maintained-by: pod-avondale
    gwcp.guidewire.com/dept: {{ .Values.departmentCode | quote }}
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: alpha
      version: {{ .Values.alpha.values.version | quote }}
  interval: 10m0s
  values: {{ toYaml .Values.alpha.values | nindent 4 }}
  postRenderers:
    - kustomize:
        # This doesn't work, `labels` isn't yet supported
        # labels:
        #   - pairs:
        #       gwcp.guidewire.com/app-name: alpha
        #       gwcp.guidewire.com/tenant-name: quadrant-shared
        patches:
          - patch: |-
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1app-name
                value: alpha
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1tenant-name
                value: quadrant-shared
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1version
                value: {{ .Values.alpha.values.version | quote }}
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1created-by
                value: pod-avondale
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1maintained-by
                value: pod-avondale
              - op: replace
                path: /metadata/labels/gwcp.guidewire.com~1dept
                value: {{ .Values.departmentCode | quote }}
            target:
              name: .*
              kind: .*
          - patch: |-
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1app-name
                value: alpha
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1tenant-name
                value: quadrant-shared
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1version
                value: {{ .Values.alpha.values.version | quote }}
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1created-by
                value: pod-avondale
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1maintained-by
                value: pod-avondale
              - op: replace
                path: /spec/template/metadata/labels/gwcp.guidewire.com~1dept
                value: {{ .Values.departmentCode | quote }}
            target:
              name: .*
              kind: Deployment
